%function y=mykeysom(x)
% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 30-May-2022 11:37:28
%
% This script assumes these variables are defined:
%
%   b - input data.

load export.mat

x = b';

% Create a Self-Organizing Map
dimension1 = 10;
dimension2 = 10;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,x);


% Test the Network
y = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)

[rows,columns] = size(y);
pos = net.layers{1}.positions;
[l,m] = size(pos);
figure, hold on%, plotsomnd(net, x)

for j=1:rows
for k=1:columns
    val = y(j,k);
    if val == 1
        n = filenames{k};
        [filepath,name,ext] = fileparts(n);
        n = name;

        val2 = pos([1,2],j);
        plot(val2(1),val2(2))
        text(val2(1),val2(2),0,n,'FontSize',15)
        
        for jj=j+1:rows
            for kk=k+1:columns
                val3 = pos([1,2],jj);
                plot([val2(1),val3(1)],[val2(2),val3(2)],'Color','y')
            end
        end
    end
        
end

end

                






           






%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

